platform :ios, '8.0'
use_frameworks!

target ‘百思不得姐’ do

pod 'Masonry', '~> 1.0.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'SVProgressHUD', '~> 2.0.3'
pod ‘MJExtension’
pod ‘MJRefresh’


end